fix: embed did not show properly when the track has no artwork attached
Fix AttributeError: 'NoneType' object has no attribute 'data' inside _audioMetadataExtractor.py due to a missing safety guard for self._tag.images.any, which cause the entire system to fail if no artwork was present.